language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
